function f_AddMaterial_For_RadBox_HFSS(oProject)
oDefinitionManager = oProject.GetDefinitionManager(); 
 invoke(oDefinitionManager,'AddMaterial', ...
    {'NAME:PMLGroup1_XYZ_1', ...    
    {'NAME:permittivity','property_type:=', 'AnisoProperty','unit:=', '','component1:=', '1.1', 'component2:=', '1.1','component3:=', '1.1'}, ... 
    {'NAME:permeability','property_type:=', 'AnisoProperty','unit:=', '','component1:=', '1.1', 'component2:=', '1.1','component3:=', '1.1'}, ... 
    {'NAME:dielectric_loss_tangent','property_type:=', 'AnisoProperty','unit:=', '','component1:=', '1', 'component2:=', '1','component3:=', '1'}, ... 
    {'NAME:magnetic_loss_tangent','property_type:=', 'AnisoProperty','unit:=', '','component1:=', '1', 'component2:=', '1','component3:=', '1'}, ... 
     });            
 
 invoke(oDefinitionManager,'AddMaterial', ...
    {'NAME:PMLGroup1_XZ_1', ...    
    {'NAME:permittivity','property_type:=', 'AnisoProperty','unit:=', '','component1:=', '1', 'component2:=', '0.01','component3:=', '1'}, ... 
    {'NAME:permeability','property_type:=', 'AnisoProperty','unit:=', '','component1:=', '1', 'component2:=', '0.01','component3:=', '1'}, ... 
    {'NAME:dielectric_loss_tangent','property_type:=', 'AnisoProperty','unit:=', '','component1:=', '0', 'component2:=', '242','component3:=', '0'}, ... 
    {'NAME:magnetic_loss_tangent','property_type:=', 'AnisoProperty','unit:=', '','component1:=', '0', 'component2:=', '242','component3:=', '0'}, ... 
     });            
 
 invoke(oDefinitionManager,'AddMaterial', ...
    {'NAME:PMLGroup1_YZ_1', ...    
    {'NAME:permittivity','property_type:=', 'AnisoProperty','unit:=', '','component1:=', '0.01', 'component2:=', '1','component3:=', '1'}, ... 
    {'NAME:permeability','property_type:=', 'AnisoProperty','unit:=', '','component1:=', '0.01', 'component2:=', '1','component3:=', '1'}, ... 
    {'NAME:dielectric_loss_tangent','property_type:=', 'AnisoProperty','unit:=', '','component1:=', '242', 'component2:=', '0','component3:=', '0'}, ... 
    {'NAME:magnetic_loss_tangent','property_type:=', 'AnisoProperty','unit:=', '','component1:=', '242', 'component2:=', '0','component3:=', '0'}, ... 
     });            
 
 invoke(oDefinitionManager,'AddMaterial', ...
    {'NAME:PMLGroup1_Z_1', ...    
    {'NAME:permittivity','property_type:=', 'AnisoProperty','unit:=', '','component1:=', '1.1', 'component2:=', '1.1','component3:=', '0.454545454545455'}, ... 
    {'NAME:permeability','property_type:=', 'AnisoProperty','unit:=', '','component1:=', '1.1', 'component2:=', '1.1','component3:=', '0.454545454545455'}, ... 
    {'NAME:dielectric_loss_tangent','property_type:=', 'AnisoProperty','unit:=', '','component1:=', '1', 'component2:=', '1','component3:=', '-1'}, ... 
    {'NAME:magnetic_loss_tangent','property_type:=', 'AnisoProperty','unit:=', '','component1:=', '1', 'component2:=', '1','component3:=', '-1'}, ... 
     });            
end