function f_AssignFiniteCond_HFSS(oProject,finCondName,objName,finCond)
% finCond: Finite Conductivity in Siemens/Meter
oDesign = oProject.SetActiveDesign('HFSSDesign1');
oModule = oDesign.GetModule('BoundarySetup');
if  isnumeric(objName)
    faceStr = sprintf('%d,',objName);
    faceStr(end) = [];
    oModule.AssignFiniteCond( ...
        { ...
        ['NAME:' finCondName],...
        'Faces:=', ...
        eval([ '{' faceStr '}' ]), ...
        'UseMaterial:=', false, ...
        'Conductivity:=', num2str(finCond), ...
        'Permeability:=', '1', ...
        'UseThickness:=', false, ...
        'Roughness:=', '0um', ...
        'InfGroundPlane:=',false ...
        } ...
        );
else
    oModule.AssignFiniteCond( ...
        { ...
        ['NAME:' finCondName],...
        'Objects:=', {objName}, ...
        'UseMaterial:=',false, ...
        'Conductivity:=', num2str(finCond), ...
        'Permeability:=', '1', ...
        'UseThickness:=',false, ...
        'Roughness:=', '0um', ...
        'InfGroundPlane:=', false ...
        } ...
        );
end
end