function f_ChangeMaterial(oEditor,name,materialVal)
oEditor.ChangeProperty(...
	{
		'NAME:AllTabs',...
		{
			'NAME:Geometry3DAttributeTab',...
			{
				'NAME:PropServers',... 
				name
			},...
			{
				'NAME:ChangedProps',...
				{
					'NAME:Material',...
					'Value:='		, [char(34) materialVal char(34)]
				}
			}
		}
	})
end