function f_CreateBox_HFSS(oProject,name,xPos,yPos,zPos,xSize,ySize,zSize,materialValue)
oDesign = oProject.SetActiveDesign('HFSSDesign1');
oEditor = oDesign.SetActiveEditor('3D Modeler');
invoke(oEditor,'CreateBox', {'NAME:BoxParameters', ...
    'XPosition:=', [ num2str(xPos) 'mm' ], 'YPosition:=',[ num2str(yPos) 'mm' ], 'ZPosition:=', [ num2str(zPos) 'mm' ], ...
    'XSize:=', [ num2str(xSize) 'mm' ], 'YSize:=', [ num2str(ySize) 'mm' ], 'ZSize:=',[ num2str(zSize) 'mm' ]}, ...
    {'NAME:Attributes', 'Name:=', name, 'Flags:=', '', 'Color:=','(132 132 193)', 'Transparency:=',0, ...
    'PartCoordinateSystem:=','Global', 'UDMId:=','', 'MaterialValue:=', ['' char(34) materialValue char(34) ''], 'SolveInside:=','True'});
end