function f_CreateRectangleParam_HFSS(oEditor,rectName,xyzStart,width,height,axisVal,materialValue)
oEditor.CreateRectangle(...
    {
    'NAME:RectangleParameters',...
    'IsCovered:='		, 'True',...
    'XStart:='		, xyzStart{1},...
    'YStart:='		, xyzStart{2},...
    'ZStart:='		, xyzStart{3},...
    'Width:='		, width,...
    'Height:='		, height,...
    'WhichAxis:='		, axisVal
    },...
    {
    'NAME:Attributes',...
    'Name:='		, rectName,...
    'Flags:='		, '',...
    'Color:='		, '(143 175 143)',...
    'Transparency:='	, 0,...
    'PartCoordinateSystem:=', 'Global',...
    'UDMId:='		, '',...
    'MaterialValue:='	, [char(34) materialValue char(34)],...
    'SurfaceMaterialValue:=', [ char(34) char(34)],...
    'SolveInside:='		, 'True',...
    'IsMaterialEditable:='	, 'True',...
    'UseMaterialAppearance:=', 'False',...
    'IsLightweight:='	, 'False'
    })
end

% function f_CreateRectangleParam_HFSS(oProject,rectName,xStart,yStart,zStart,width,height,axis,partCoodSys,materialValue)
% oDesign = oProject.SetActiveDesign('HFSSDesign1');
% oEditor = oDesign.SetActiveEditor('3D Modeler');
%
% invoke(oEditor,'CreateRectangle', {'NAME:RectangleParameters', 'IsCovered:=', 'True', 'XStart:=',[ num2str(xStart) 'mm' ], 'YStart:=', [ num2str(yStart) 'mm' ], 'ZStart:=', [ num2str(zStart) 'mm' ], ...
%     'Width:=', [ num2str(width) 'mm' ], 'Height:=',[ num2str(height) 'mm' ], 'WhichAxis:=', axis}, {'NAME:Attributes', 'Name:=', rectName, 'Flags:=',  ...
%     '', 'Color:=', '(132 132 193)', 'Transparency:=', 0, 'PartCoordinateSystem:=',  ...
%     partCoodSys, 'UDMId:=', '', 'MaterialValue:=', ['' char(34) materialValue char(34) ''], 'SolveInside:=','True'})
%
% end