function f_CreatePolyline(oProject,activeDsg,materialValue,linName,pointList)
oDesign       = oProject.SetActiveDesign(activeDsg);
oEditor       = oDesign.SetActiveEditor('3D Modeler');
ptListCell    = [];
ptListSegCell = [];
%-- Create line points
ptListCell{1} = 'NAME:PolylinePoints';
for ind = 1:size(pointList,1)
    ptListCell{ind+1} = [{'NAME:PLPoint'}    {'X:='}    {[num2str(pointList(ind,1),'%f') 'mm']}    {'Y:='}    {[num2str(pointList(ind,2),'%f') 'mm']}    {'Z:='}    {[num2str(pointList(ind,3),'%f') 'mm']}];
end

ptListSegCell{1} = 'NAME:PolylineSegments';
for ind = 1:size(pointList,1)-1
    ptListSegCell{ind+1} =  [{'NAME:PLSegment'}    {'SegmentType:='}    {'Line'}    {'StartIndex:='}    {[ind-1]}    {'NoOfPoints:='}    {[2]}];
end

invoke(oEditor,'CreatePolyline', ...
    { ...
    'NAME:PolylineParameters', ...
    'IsPolylineCovered:='	, true, ...
    'IsPolylineClosed:='	, false, ...
    ptListCell, ...
    ptListSegCell, ...
    { ...
    'NAME:PolylineXSection', ...
    'XSectionType:='	, 'None', ...
    'XSectionOrient:='	, 'Auto', ...
    'XSectionWidth:='	, '0mm', ...
    'XSectionTopWidth:='	, '0mm', ...
    'XSectionHeight:='	, '0mm', ...
    'XSectionNumSegments:='	, '0', ...
    'XSectionBendType:='	, 'Corner' ...
    } ...
    },  ...
    { ...
    'NAME:Attributes', ...
    'Name:='		, linName, ...
    'Flags:='		, '', ...
    'Color:='		, '(143 175 143)', ...
    'Transparency:='	, 0, ...
    'PartCoordinateSystem:=', 'Global', ...
    'UDMId:='		, '', ...
    'MaterialValue:='	, ['' char(34) materialValue char(34) ''], ...
    'SurfaceMaterialValue:=', ['' char(34) '' char(34) ''], ...
    'SolveInside:='		, false, ...
    'IsMaterialEditable:='	, true, ...
    'UseMaterialAppearance:=', false, ...
    'IsLightweight:='	, false ...
    });
end