function f_CreatePort_HFSS(oProject,name,faceNum,numModes,bUseAnalyticAlignment,varargin)
oDesign = oProject.SetActiveDesign('HFSSDesign1');
oModule = oDesign.GetModule('BoundarySetup');
%--
modeCell      = cell(1,4);
modeNumCell   = cell(numModes,5);
modeCell{1,1} = 'NAME:Modes';
for modeInd = 1:numModes
    modeNumCell{modeInd,1} = [ 'NAME:Mode' num2str(modeInd) ];
    modeNumCell{modeInd,2} = 'ModeNum:=';
    modeNumCell{modeInd,3} = modeInd;
    modeNumCell{modeInd,4} = 'UseIntLine:=';
    modeNumCell{modeInd,5} = 'false';
    modeCell{1,modeInd+1}  = modeNumCell(modeInd,:);
end
%--
trueStr = [];
for modeNumInd = 1:numModes
    trueStr = sprintf('%s true,',trueStr);
end
trueStr(end) = [];
%--
switch bUseAnalyticAlignment
    case false
        oModule.AssignWavePort( ...
            { ...
            [ 'NAME:' name ], ...
            'Faces:=', {faceNum}, ...
            'NumModes:=', numModes, ...
            'RenormalizeAllTerminals:=','true', ...
            'UseLineModeAlignment:=', 'false', ...
            'DoDeembed:=', 'false', ...
            modeCell, ...
            'ShowReporterFilter:=','false', ...
            'ReporterFilter:=', eval(['{' trueStr '}']), ...
            'UseAnalyticAlignment:=',bUseAnalyticAlignment ...
            } ...
            );
        
    case true
        stPt  = varargin{1,1};
        endPt = varargin{1,2};
        bAnalyticReverseV = varargin{1,3};
        bDoDeembed = varargin{1,4};
        DeembedDist = varargin{1,5};
        oModule.AssignWavePort( ...
            { ...
            [ 'NAME:' name ], ...
            'Faces:=',{faceNum}, ...
            'NumModes:=', numModes, ...
            'RenormalizeAllTerminals:=',true, ...
            'UseLineModeAlignment:=', false, ...
            'DoDeembed:=', bDoDeembed, ...
            'DeembedDist:=',[ num2str(DeembedDist) 'mm'], ...                                    
            modeCell, ...
            'ShowReporterFilter:=', false, ...
            'ReporterFilter:=', eval(['{' trueStr '}']), ...
            'UseAnalyticAlignment:=',bUseAnalyticAlignment, ...
            { ...
            'NAME:AnalyticULine', ...
            'Start:=', {[ num2str(stPt(1)) 'mm'],[ num2str(stPt(2)) 'mm'], [ num2str(stPt(3)) 'mm']}, ...
            'End:=', {[ num2str(endPt(1)) 'mm'], [ num2str(endPt(2)) 'mm'], [ num2str(endPt(3)) 'mm']} ...
            }, ...
            'AnalyticReverseV:=',bAnalyticReverseV ...
            } ...
            );
end
end