function f_CreateInitialMesh_HFSS(oProject,surfDev)
oDesign = oProject.SetActiveDesign('HFSSDesign1');
oModule = oDesign.GetModule('MeshSetup');
oModule.InitialMeshSettings ( ...
    { ...
    'NAME:MeshSettings', ...
        { ...
        'NAME:GlobalSurfApproximation', ...
        'SurfDevChoice:=',2, ...
        'SurfDev:=', [ num2str(surfDev) 'mm'], ...
        'NormalDevChoice:=', 1, ...
        'AspectRatioChoice:=', 1, ...
        'PullToTrueSurf:=', true, ...
        'SetFacePreservationLevel:=', 0 ...
        }, ...
    'MeshMethod:=', 'Auto' ...
    } ...
    );