function f_CreateBox_Param_HFSS(oProject,name,xPos,yPos,zPos,xSize,ySize,zSize,materialValue,transp)
oDesign = oProject.SetActiveDesign('HFSSDesign1');
oEditor = oDesign.SetActiveEditor('3D Modeler');
invoke(oEditor,'CreateBox', {'NAME:BoxParameters', ...
    'XPosition:=', xPos, 'YPosition:=',yPos, 'ZPosition:=', zPos, ...
    'XSize:=', xSize, 'YSize:=', ySize, 'ZSize:=',zSize}, ...
    {'NAME:Attributes', 'Name:=', name, 'Flags:=', '', 'Color:=','(132 132 193)', 'Transparency:=',transp, ...
    'PartCoordinateSystem:=','Global', 'UDMId:=','', 'MaterialValue:=', ['' char(34) materialValue char(34) ''], 'SolveInside:=','True'});
end