function f_CreateCylinder_HFSS(oProject,activeDsg,name,xCenter,yCenter,zCenter,radius,height,axisDir,materialValue)
oDesign       = oProject.SetActiveDesign(activeDsg);
oEditor       = oDesign.SetActiveEditor('3D Modeler');
invoke(oEditor,'CreateCylinder',{'NAME:CylinderParameters', ...
    'XCenter:=', [ num2str(xCenter) 'mm'], 'YCenter:=',[ num2str(yCenter) 'mm'], 'ZCenter:=', [ num2str(zCenter) 'mm'], ...
    'Radius:=', [ num2str(radius) 'mm'], 'Height:=',[ num2str(height) 'mm'], 'WhichAxis:=', axisDir, 'NumSides:=', '0'}, ...
    {'NAME:Attributes', 'Name:=',name, 'Flags:=', '', 'Transparency:=', 0, 'PartCoordinateSystem:=','Global', 'UDMId:=', '', ...
    'MaterialValue:=', ['' char(34) materialValue char(34) ''], 'SolveInside:=','True'});
end


% invoke(oEditor,'CreateCylinder',{'NAME:CylinderParameters', ...
%     'XCenter:=', [ num2str(xCenter) 'mm'], 'YCenter:=',[ num2str(yCenter) 'mm'], 'ZCenter:=', [ num2str(zCenter) 'mm'], ...
%     'Radius:=', [ num2str(radius) 'mm'], 'Height:=',[ num2str(height) 'mm'], 'WhichAxis:=', axisDir, 'NumSides:=', '0'}, ...
%     {'NAME:Attributes', 'Name:=',name, 'Flags:=', '', 'Color:=', '(132 132 193)', 'Transparency:=', 0, 'PartCoordinateSystem:=','Global', 'UDMId:=', '', ...
%     'MaterialValue:=', ['' char(34) materialValue char(34) ''], 'SolveInside:=','True'});