function f_DuplicateAroundAxis(oEditor,name,axisVal,angleDeg,numClones)
oEditor.DuplicateAroundAxis(...
    {
    'NAME:Selections',...
    'Selections:='		, name,...
    'NewPartsModelFlag:='	, 'Model'
    },...
    {
    'NAME:DuplicateAroundAxisParameters',...
    'CreateNewObjects:='	, 'True',...
    'WhichAxis:='		, axisVal,...
    'AngleStr:='		, [ num2str(angleDeg) 'deg'],...
    'NumClones:='		, num2str(numClones)
    },...
    {
    'NAME:Options',...
    'DuplicateAssignments:=', 'False'
    },...
    {
    'CreateGroupsForNewObjects:=', 'False'
    });
end