function f_DuplicateMirror_HFSS(oProject,partName,vBase,vNormal)
oDesign = oProject.SetActiveDesign('HFSSDesign1');
oEditor = oDesign.SetActiveEditor('3D Modeler');
invoke(oEditor,'DuplicateMirror',{'NAME:Selections', 'Selections:=', partName, 'NewPartsModelFlag:=',  ...
    'Model'}, {'NAME:DuplicateToMirrorParameters', 'DuplicateMirrorBaseX:=', [ num2str(vBase(1)) '0mm'], 'DuplicateMirrorBaseY:=',  ...
    [ num2str(vBase(2)) '0mm'], 'DuplicateMirrorBaseZ:=', [ num2str(vBase(3)) '0mm'], 'DuplicateMirrorNormalX:=', [ num2str(vNormal(1)) '0mm'], 'DuplicateMirrorNormalY:=',  ...
    [ num2str(vNormal(2)) '0mm'], 'DuplicateMirrorNormalZ:=', [ num2str(vNormal(3)) '0mm']}, {'NAME:Options', 'DuplicateAssignments:=', false});
end