function f_InsertOptimizationSetup(oProject,optName,sphereName,thetaDeg,gain_dB)

oDesign = oProject.SetActiveDesign('HFSSDesign1');
oModule = oDesign.GetModule('Optimetrics');
% oModule.InsertSetup('OptiOptimization', {'NAME:OptimizationSetup111', 'IsEnabled:=',  ...
%     true, {'NAME:ProdOptiSetupData', 'SaveFields:=', false, 'CopyMesh:=', false}, {'NAME:StartingPoint'}, 'Optimizer:=',  ...
%     'Quasi Newton', {'NAME:AnalysisStopOptions', 'StopForNumIteration:=', true, 'StopForElapsTime:=',  ...
%     false, 'StopForSlowImprovement:=', false, 'StopForGrdTolerance:=', false, 'MaxNumIteration:=',  ...
%     1000, 'MaxSolTimeInSec:=', 3600, 'RelGradientTolerance:=', 0, 'MinNumIteration:=',  ...
%     10}, 'CostFuncNormType:=', 'L2', 'PriorPSetup:=', '', 'PreSolvePSetup:=', true, {'NAME:Variables'}, {'NAME:LCS'}, {'NAME:Goals', {'NAME:Goal', 'ReportType:=',  ...
%     'Far Fields', 'Solution:=', 'Setup1 : LastAdaptive', {'NAME:SimValueContext', 'Context:=',  ...
%     'Opt - Infinite Sphere'}, 'Calculation:=', 'dB10normalize(GainRHCP)', 'Name:=',  ...
%     'dB10normalize(GainRHCP)', {'NAME:Ranges', 'Range:=', {'Var:=', 'Theta', 'Type:=','d', ...
%     'DiscreteValues:=','-75deg,-70deg,-65deg,-60deg,-55deg,-50deg,-45deg,-40deg,-35deg,-30deg,-25deg,-20deg,-15deg,-10deg,-5deg,0deg,5deg,10deg,15deg,20deg,25deg,30deg,35deg,40deg,45deg,50deg,55deg,60deg,65deg,70deg,75deg'}, ...
%     'Range:=', {'Var:=', 'Phi', 'Type:=','d', 'DiscreteValues:=', '0deg'}, 'Range:=', {'Var:=', 'Freq', 'Type:=','d', 'DiscreteValues:=', '2.3GHz'}}, 'Condition:=', '==', ...
%     {'NAME:GoalValue', 'GoalValueType:=','Dependent', 'Format:=', 'Real/Imag', 'Variable:=', 'Theta', ...
%     'bG:=', {'ix:=','-75', 'v:=', '[-100;]'}, 'bG:=', {'ix:=', '-70', 'v:=', '[-1150;]'}, 'bG:=', {'ix:=','-65', 'v:=', '[-110;]'}, 'bG:=', {'ix:=', '-60', 'v:=', '[-119;]'}}, 'Weight:=', '[1;]'}}, ...
%     'Acceptable_Cost:=', 0, 'Noise:=', 0.0001, 'UpdateDesign:=', false, 'UpdateIteration:=',5,'KeepReportAxis:=', true, 'UpdateDesignWhenDone:=', true});
%

thetaDegRangeStr = [];
radPattStr1 = [];
% thetaDeg = [ -75 -70 -65 -60]
% gain_dB = [-10 -8 -6 -4]
for ind = 1:numel(thetaDeg)
    radPattStr1 = sprintf('%s''bG:='', {''ix:='', ''%d'', ''v:='', ''[%d;]''},''',radPattStr1,thetaDeg(ind),gain_dB(ind));
    thetaDegRangeStr = sprintf('%s%ddeg,',thetaDegRangeStr,thetaDeg(ind));
end
thetaDegRangeStr(end) = [];
radPattStr1(end-1:end) = [];
radPattStr2 = strrep(radPattStr1, '''''', '''');
radPattStr  = sprintf('%s''}, ''Weight:='', ''[1;]''}},',radPattStr2);
radPattStr  = sprintf('{''NAME:GoalValue'', ''GoalValueType:='',''Dependent'', ''Format:='', ''Real/Imag'', ''Variable:='', ''Theta'',%s''}',radPattStr2);



oModule.InsertSetup('OptiOptimization', {['NAME:' optName], 'IsEnabled:=',  ...
    true, {'NAME:ProdOptiSetupData', 'SaveFields:=', false, 'CopyMesh:=', false}, {'NAME:StartingPoint'}, 'Optimizer:=',  ...
    'Quasi Newton', {'NAME:AnalysisStopOptions', 'StopForNumIteration:=', true, 'StopForElapsTime:=',  ...
    false, 'StopForSlowImprovement:=', false, 'StopForGrdTolerance:=', false, 'MaxNumIteration:=',  ...
    1000, 'MaxSolTimeInSec:=', 3600, 'RelGradientTolerance:=', 0, 'MinNumIteration:=',  ...
    10}, 'CostFuncNormType:=', 'L2', 'PriorPSetup:=', '', 'PreSolvePSetup:=', true, {'NAME:Variables'}, {'NAME:LCS'}, {'NAME:Goals', {'NAME:Goal', 'ReportType:=',  ...
    'Far Fields', 'Solution:=', 'Setup1 : LastAdaptive', {'NAME:SimValueContext', 'Context:=',  ...
    sphereName}, 'Calculation:=', 'dB10normalize(GainRHCP)', 'Name:=',  ...
    'dB10normalize(GainRHCP)', {'NAME:Ranges', 'Range:=', {'Var:=', 'Theta', 'Type:=','d', ...
    'DiscreteValues:=',thetaDegRangeStr}, ...
    'Range:=', {'Var:=', 'Phi', 'Type:=','d', 'DiscreteValues:=', '0deg'}, 'Range:=', {'Var:=', 'Freq', 'Type:=','d', 'DiscreteValues:=', '2.3GHz'}}, 'Condition:=', '==', ...
    eval(radPattStr) ...
    , 'Weight:=', '[1;]'}}, ...
    'Acceptable_Cost:=', 0, 'Noise:=', 0.0001, 'UpdateDesign:=', false, 'UpdateIteration:=',5,'KeepReportAxis:=', true, 'UpdateDesignWhenDone:=', true});
end