function f_InsertSetup_HFSS(oProject,name,adaptFreq,minNumPass,maxNumPass,percentRefinement,maxDeltaS,basisOrder)
oDesign = oProject.SetActiveDesign('HFSSDesign1');
oModule = oDesign.GetModule('AnalysisSetup');
oModule.InsertSetup ('HfssDriven', ...
    {['NAME:' name ], ...
    'Frequency:=', [ num2str(adaptFreq) 'GHz' ], ...
    'PortsOnly:=',false,  ...
    'MaxDeltaS:=', maxDeltaS,  ...
    'UseMatrixConv:=', false,  ...
    'MaximumPasses:=',maxNumPass,  ...
    'MinimumPasses:=',minNumPass,  ...
    'MinimumConvergedPasses:=', 1,  ...
    'PercentRefinement:=', percentRefinement,  ...
    'IsEnabled:=',true,  ...
    'BasisOrder:=', basisOrder,  ...
    'UseIterativeSolver:=', false,  ...
    'DoLambdaRefine:=',true,  ...
    'DoMaterialLambda:=', true,  ...
    'SetLambdaTarget:=', false,  ...
    'Target:=',0.6667,  ... 
    'UseMaxTetIncrease:=', false,  ...
    'PortAccuracy:=', 2,  ...
    'UseABCOnPort:=',false,  ...
    'SetPortMinMaxTri:=', false,  ...
    'EnableSolverDomains:=', false,  ...
    'SaveRadFieldsOnly:=',false,  ...
    'SaveAnyFields:=', true,  ...
    'NoAdditionalRefinementOnImport:=', false});
end