function f_InsertFrequencySweep_HFSS(oProject,setupName,name,type,stFreq,endFreq,numCount)
oDesign = oProject.SetActiveDesign('HFSSDesign1');
oModule = oDesign.GetModule('AnalysisSetup');
oModule.InsertFrequencySweep(...
    setupName, ...
    {[ 'NAME:' name ], ...
    'IsEnabled:=', true, ...
    'SetupType:=','LinearCount', ...
    'StartValue:=', [ num2str(stFreq) 'GHz' ], ...
    'StopValue:=',  [ num2str(endFreq) 'GHz' ], ...
    'Count:=', numCount, ...
    'Type:=',type, ...
    'SaveFields:=', false, ...
    'SaveRadFields:=', false, ...
    'InterpTolerance:=', 0.5, ...
    'InterpMaxSolns:=', 250, ...
    'InterpMinSolns:=', 0, ...
    'InterpMinSubranges:=', 1, ...
    'ExtrapToDC:=',false, ...
    'InterpUseS:=', true, ...
    'InterpUsePortImped:=', false, ...
    'InterpUsePropConst:=',true, ...
    'UseDerivativeConvergence:=', false, ...
    'InterpDerivTolerance:=', 0.2, ...
    'UseFullBasis:=',true, ...
    'EnforcePassivity:=', false ...
    });
end