function f_Scale_HFSS(oProject,activeDsg,name,scaleFactor)
oDesign       = oProject.SetActiveDesign(activeDsg);
oEditor       = oDesign.SetActiveEditor('3D Modeler');
oEditor.Scale({ ...
		'NAME:Selections', ...
		'Selections:='		, name, ...
		'NewPartsModelFlag:='	, 'Model' ...
	}, ... 
	{ ...
		'NAME:ScaleParameters', ...
		'ScaleX:='		, num2str(scaleFactor(1)), ...
		'ScaleY:='		, num2str(scaleFactor(2)), ...
		'ScaleZ:='		, num2str(scaleFactor(3)) ...
	});
end