function f_StoreProjectParameter_HFSS(oProject,name,value,unit)
invoke(oProject,'ChangeProperty', {'NAME:AllTabs', {'NAME:ProjectVariableTab',...
    {'NAME:PropServers','ProjectVariables'},...
    {'NAME:NewProps', {[ 'NAME:$' name ], 'PropType:=','VariableProp', 'UserDef:=', true, 'Value:=', [ num2str(value) unit]}}...
    }});
end