function f_SubtractSolids_HFSS(oProject,activeDsg,name1,name2,bKeepOriginals)
oDesign = oProject.SetActiveDesign(activeDsg);
oEditor = oDesign.SetActiveEditor('3D Modeler');
oEditor.Subtract( {'NAME:Selections',...
    'Blank Parts:=', name1,...
    'Tool Parts:=', name2},...
    {'NAME:SubtractParameters', 'KeepOriginals:=', bKeepOriginals});
end