function f_SetInitialDistribution(oMWS,distributionType,optimizerType)
% For the featured global optimization techniques and the  Nelder Mead Simplex Algorithm 
% a set of initial points in the parameter space are necessary. These points will automatically
% be generated by a uniform random distribution generator or by the Latin Hypercube approach.
% 
% Uniform Random Numbers:  For each starting point a pseudo random number generator will choose 
% uniformly distributed points in the parameter space.
% Latin Hypercube:  Randomly chosen points sometimes have the disadvantage that they do not have
% optimal space filling properties in the parameter space. The Latin Hypercube sampling has the
% special property that a projection onto each parameter interval yields an equidistant sampling.
% Noisy Latin Hypercube Distribution:  The initial points are distributed similar to the Latin
% Hypercube Distribution but a perturbation is added on each point. This distribution type has
% similar space filling properties as the Latin Hypercube Distribution but the generated point
% set will be less regular. This distribution type is only available for the Nelder Mead Simplex Algorithm. 
% 
% distributionType: 'Uniform_Random_Numbers', 'Latin_Hyper_Cube', 'Noisy_Latin_Hyper_Cube', 'Cube_Distribution'
% optimizerType   : 'Genetic_Algorithm', 'Particle_Swarm', 'Nelder_Mead_Simplex'
oOptimizer = invoke(oMWS,'Optimizer');
invoke(oOptimizer,'SetInitialDistribution',distributionType,optimizerType);
end