function f_GenerateLatexFileForFigures(latexFileName,fileNameWithCaption,figSizeVar)
fid = fopen(latexFileName,'wt');
if fid == -1
    fprintf(1,'Unable to open %s ',latexFileName);    
end
fprintf(fid,'%%Date-Month-Year-Hour-Min-:%s, Generated by FAROOQUI Muhammad Zunnoorain from MATLAB',dataTimeString);
for ind = 1:size(fileNameWithCaption,1)
fprintf(fid,'\n\\begin{figure}[h]');
fprintf(fid,'\n\t\\centering');	
fprintf(fid,'\n\t\\includegraphics[width=%s,keepaspectratio]{%s}',figSizeVar,fileNameWithCaption{ind,1});	
fprintf(fid,'\n\t\\caption{%s}',fileNameWithCaption{ind,2});
fprintf(fid,'\n\t\\label{fig:%s}',fileNameWithCaption{ind,1});	
fprintf(fid,'\n\\end{figure}');	
end
fprintf(fid,'\n\\FloatBarrier %% add \\usepackage[section]{placeins} in order to flush all fig');	
fclose(fid);
end