function f_SaveInPDF_And_GenerateLatexFile(latexFileName,fileNameWithCaption,figSizeVar)
%-- Save in PDF
matlabVersion = version;
if strcmp(matlabVersion,'8.6.0.267246 (R2015b)')
    hFigs = sort(findobj('Type','figure'),2);
    totFigNum = size(findobj('Type','figure'),1);
    
    for indFig = 1:totFigNum
        figNumbers(indFig) = hFigs(indFig).Number;
    end
    sFigNumbers = sort(figNumbers);
    
    for indFig = 1:totFigNum
        figure(sFigNumbers(indFig))
        hFigure = gcf;
        set(hFigure.Number,'Units','Inches');
        pos = get(hFigure.Number,'Position');
        set(hFigure.Number,'PaperPositionMode','Auto','PaperUnits','Inches','PaperSize',[pos(3), pos(4)])
        print(hFigure,[fileNameWithCaption{indFig,1} '.pdf'],'-dpdf','-r0')
    end
else
    hFigs = sort(findobj('Type','figure'));
    for indFig = 1:length(hFigs)
        set(hFigs(indFig),'Units','Inches');
        pos = get(hFigs(indFig),'Position');
        set(hFigs(indFig),'PaperPositionMode','Auto','PaperUnits','Inches','PaperSize',[pos(3), pos(4)])
        print(hFigs(indFig),[fileNameWithCaption{indFig,1} '.pdf'],'-dpdf','-r0')
    end
end
%-- Generate latex script
fid = fopen(latexFileName,'wt');
if fid == -1
    fprintf(1,'Unable to open %s ',latexFileName);
end
fprintf(fid,'%%Date-Month-Year-Hour-Min-:%s, Generated by FAROOQUI Muhammad Zunnoorain from MATLAB',dataTimeString);
for ind = 1:size(fileNameWithCaption,1)
    fprintf(fid,'\n\\begin{figure}[h]');
    fprintf(fid,'\n\t\\centering');
    fprintf(fid,'\n\t\\includegraphics[width=%s,keepaspectratio]{%s}',figSizeVar,fileNameWithCaption{ind,1});
    fprintf(fid,'\n\t\\caption{%s}',fileNameWithCaption{ind,2});
    fprintf(fid,'\n\t\\label{fig:%s}',fileNameWithCaption{ind,1});
    fprintf(fid,'\n\\end{figure}');
end
fprintf(fid,'\n\\FloatBarrier %% add \\usepackage[section]{placeins} in order to flush all fig');
fclose(fid);
end
%------------------------------------------
% LOCAL FUNCTION
%------------------------------------------
function dataTimeStr = dataTimeString()
c = clock;
[token1, remain1] = strtok(date,'-');
[token2, remain2] = strtok(remain1,'-');
[token3, remain3] = strtok(remain2,'-');
dataTimeStr = [ token1 token2 token3 '_' num2str(c(4)) '_' num2str(c(5)) ];
end