close all;clear all;clc;
touchStoneFN = 'F:\FAROOQUI\MEASUREMENT_DATA\OCE\8x8 Patch\AD260\27Aug2018\Matching_8x8_PatchArray_AD260.s2p';
datFN = [strtok(touchStoneFN,'.') '_FOR_DAMS.dat'];
sParamData = sparameters(touchStoneFN);
s11  = squeeze(sParamData.Parameters(1,1,:));
freq = sParamData.Frequencies;
figure,plot(freq,20*log10(abs(s11)));grid on;xlabel('freq');ylabel('s_{11}[dB]')
sizeData = numel(freq);
fid = fopen(datFN,'w');
fprintf(fid,'\nS22');
fprintf(fid,'\nNotes to be saved with Reg3');
fprintf(fid,'\nNotes to be saved with Reg2');
fprintf(fid,'\nNotes to be saved with Reg4');
fprintf(fid,'\n(Record');
fprintf(fid,'\n (numDims 1)');
fprintf(fid,'\n (size 2)');
fprintf(fid,'\n (schema');
fprintf(fid,'\n  (numFields 6)');
fprintf(fid,'\n  (fieldName "Mag"');
fprintf(fid,'\n   (type Real64)');
fprintf(fid,'\n   (numDims 1)');
fprintf(fid,'\n   (size %d)',sizeData);
fprintf(fid,'\n  )');
fprintf(fid,'\n  (fieldName "Phase"');
fprintf(fid,'\n   (type Real64)');
fprintf(fid,'\n   (numDims 1)');
fprintf(fid,'\n   (size %d)',sizeData);
fprintf(fid,'\n  )');
fprintf(fid,'\n  (fieldName "Hpos"');
fprintf(fid,'\n   (type Real64)');
fprintf(fid,'\n  )');
fprintf(fid,'\n  (fieldName "Vpos"');
fprintf(fid,'\n   (type Real64)');
fprintf(fid,'\n  )');
fprintf(fid,'\n  (fieldName "HV"');
fprintf(fid,'\n   (type Real64)');
fprintf(fid,'\n  )');
fprintf(fid,'\n  (fieldName "Freq"');
fprintf(fid,'\n   (type Real64)');
fprintf(fid,'\n   (numDims 1)');
fprintf(fid,'\n   (size %d)',sizeData);
fprintf(fid,'\n  )');
fprintf(fid,'\n )');
fprintf(fid,'\n (data ');
fprintf(fid,'\n  (record');
fprintf(fid,'\n   ( "Mag"');
fprintf(fid,'\n    [');
fprintf(fid,' %f ',abs(s11));
fprintf(fid,']');
fprintf(fid,'\n   )');
fprintf(fid,'\n   ( "Phase"');
fprintf(fid,'\n    [');
fprintf(fid,' %f ',rad2deg(angle(s11)));
fprintf(fid,']');
fprintf(fid,'\n   )');
fprintf(fid,'\n   ( "Hpos" 0)');
fprintf(fid,'\n   ( "Vpos" 0)');
fprintf(fid,'\n   ( "HV" 0)');
fprintf(fid,'\n   ( "Freq"');
fprintf(fid,'\n    [');
fprintf(fid,' %f ',freq);
fprintf(fid,']');
fprintf(fid,'\n   )');
fprintf(fid,'\n)  ');
% fprintf(fid,'\n)');
% fprintf(fid,'\n)');
fprintf(fid,'\n  (record');
fprintf(fid,'\n   ( "Mag"');
fprintf(fid,'\n    [');
fprintf(fid,' %f ',abs(s11));
fprintf(fid,']');
fprintf(fid,'\n   )');
fprintf(fid,'\n   ( "Phase"');
fprintf(fid,'\n    [');
fprintf(fid,' %f ',rad2deg(angle(s11)));
fprintf(fid,']');
fprintf(fid,'\n   )');
fprintf(fid,'\n   ( "Hpos" 360)');
fprintf(fid,'\n   ( "Vpos" 0)');
fprintf(fid,'\n   ( "HV" 0)');
fprintf(fid,'\n   ( "Freq"');
fprintf(fid,'\n    [');
fprintf(fid,' %f ',freq);
fprintf(fid,']');
fprintf(fid,'\n   )');
fprintf(fid,'\n)  ');
fprintf(fid,'\n)');
fprintf(fid,'\n)');
fprintf(fid,'\n(Real64');
fprintf(fid,'\n(data  0)');
fprintf(fid,'\n)');
fprintf(fid,'\n(Real64');
fprintf(fid,'\n(data  0)');
fprintf(fid,'\n)');
fprintf(fid,'\n(Real64');
fprintf(fid,'\n(data  0)');
fprintf(fid,'\n)');
fprintf(fid,'\n(Real64');
fprintf(fid,'\n(data  0)');
fprintf(fid,'\n)');
fclose(fid);